<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '2.2.2';
$moduleRevision = '18a0e400746dc3eb185e46db994e64923fcde02d';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/DirectAdmin_Extended_For_WHMCS';