<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.1.2';
$moduleRevision = 'bf7c2d1e56085aa355508677ce5b271941b53330';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/';